plugins {
    id 'java'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
    maven { url 'https://frcmaven.wpi.edu/artifactory/release/' }
}

dependencies {
    compileOnly('org.deltacv.EOCV-Sim:Common:4.2.0') { transitive = false }
    compileOnly('org.deltacv.EOCV-Sim:Vision:4.2.0') { transitive = false }
	
    compileOnly 'org.wpilib.thirdparty.opencv:opencv-java:2027-4.13.0-3'
}
